version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    network_mode: host
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha37
    network_mode: host
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@localhost:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
      ## uncomment next line to set an access key
      # HASURA_GRAPHQL_ACCESS_KEY: mysecretaccesskey
    env_file:
      - event-triggers.env


